In [44]:
import numpy as np

In [45]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # all | last | last_expr | none 

2.1 The Interpreter

In [46]:
10

10

In [47]:
a=10
b=np.sin(a)

In [48]:
a
b

10

-0.54402111088936977

2.2 The editor

In [49]:
run instructions.py

In [50]:
a

11

3.1 Creating matrices

In [51]:
a=5
a

5

In [52]:
y=np.array([0, 5, 10, 15, 20])
y

array([ 0,  5, 10, 15, 20])

In [53]:
x=np.array([0, 5, 10, 15, 20])
x=x.reshape(x.size,1)
x

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [54]:
A=np.array([[0,1,2,3,4], [5,6,7,8,9], [10, 11, 12, 13, 14],[15, 16, 17, 18, 19] ])
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
B=np.arange(20).reshape(4,5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
run Amatrix

ERROR:root:File `'Amatrix.py'` not found.


3.2 Matrix operations

In [57]:
y+y

array([ 0, 10, 20, 30, 40])

In [58]:
x+x

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

3.3 Matrix functions

In [59]:
b=np.dot(A,x)
b

array([[150],
       [400],
       [650],
       [900]])

In [60]:
I=np.eye(2)
I

array([[ 1.,  0.],
       [ 0.,  1.]])

In [61]:
n=np.arange(1,6)
n

array([1, 2, 3, 4, 5])

In [62]:
n=np.arange(1,6,2)
n

array([1, 3, 5])

In [63]:
y=np.arange(0,21,5)
y

array([ 0,  5, 10, 15, 20])

3.4 Indexing matrices

In [64]:
A
A[1,2]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

7

In [65]:
nr=np.size(A,0)
nc=np.size(A,1)
nr
nc

4

5

In [66]:
A[1,0:nc]
A[1,:]

array([5, 6, 7, 8, 9])

array([5, 6, 7, 8, 9])

In [67]:
A[1,:-1]

array([5, 6, 7, 8])

In [68]:
np.hstack((a,y))

array([ 5,  0,  5, 10, 15, 20])

3.5 Logical operators

In [69]:
y>=10

array([False, False,  True,  True,  True], dtype=bool)

In [70]:
idx=np.where(y >= 10)
idx

(array([2, 3, 4], dtype=int64),)

3.6 Exercises

a)

In [71]:
a=5
x=np.arange(0,21,5).reshape((np.size(x,0),-1))
y=np.arange(0,21,5)
A=np.arange(0,21)
A=np.resize(A,(4,5))
a
x
y
A

5

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

array([ 0,  5, 10, 15, 20])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

b)

In [72]:
a+a
a+y
a*y
a*A
print('x*A gives error')
np.multiply(A,A)


10

array([ 5, 10, 15, 20, 25])

array([  0,  25,  50,  75, 100])

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

x*A gives error


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

c)

In [73]:
B=A[:,:-1]
B

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [74]:
np.linalg.det(B)
np.diag(A)
np.diag(np.diag(A))

-2.052683297350821e-46

array([ 0,  6, 12, 18])

array([[ 0,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 12,  0],
       [ 0,  0,  0, 18]])

d)

In [75]:
I=np.eye(3)
I

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

e)

In [76]:
x=np.arange(1,101)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

f)

In [77]:
A[0::2,1]

array([ 1, 11])

g) 

In [78]:
A[1:-1,1:-1]

array([[ 6,  7,  8],
       [11, 12, 13]])

h)

In [79]:
np.vstack((A,y))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  5, 10, 15, 20]])

i)

In [80]:
y
idx=np.where(y>15)
y[idx]

array([ 0,  5, 10, 15, 20])

array([20])

j)

In [81]:
import scipy.io as io
mat = io.loadmat('nucseq.mat')

In [82]:
nucseq=mat.get('nucseq')
n=nucseq[0]
n[1:10]
len(n)

'atcaattca'

13001

Make array ,b, of binary sequences, one for each row
A smaller copy, b2, is made for easier handling 

In [83]:
b=np.zeros((4,len(n)))
b2=b[:,0:10] # smaller copy
b2
np.shape(b)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

(4, 13001)

In [84]:
# Solve small scale problem
bases=['a','t','c','g']
n2=n[0:10]
n2
for i in range(0,4):
    idx=[x for x, v in enumerate(n2) if v == bases[i]]
    b2[i,idx]=1
    b2

'aatcaattca'

array([[ 1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

array([[ 1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

array([[ 1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

array([[ 1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [85]:
# Full scale solution
bases=['a','t','c','g']
n[0:10]
for i in range(0,4):
    idx=[x for x, v in enumerate(n) if v == bases[i]]
    b[i,idx]=1

'aatcaattca'

In [ ]:
n[0:40]
b[:,0:40]