5 Programming

In [10]:
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # all | last | last_expr | none 

In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


5.1 Function files

In [16]:
def pdens(x, m, s):
    print('Hello')
    p = 1 / (np.sqrt(2 * np.pi) * s) * \
        np.exp(-1 / 2 * np.square((x - m)) / (2 * np.square(s)))

    return p

p=pdens(1,2,3)
p

Hello


0.12933768267647971

Put the definition in the module pyfuns.py and import it from there.  The following show variants on how to import the definition

In [19]:
from pyfuns import pdens 
p=pdens(1,2,3)
p

0.12933768267647971

In [17]:
from pyfuns import pdens as pd 
p=pd(1,2,3)
p

0.12933768267647971

In [21]:
import pyfuns 
p=pyfuns.pdens(1,2,3)
p

0.12933768267647971

5.2 Control structures

5.2.1 Conditional testing with if

In [24]:
def absolute(x):
    if x < 0:
        y = -x
    else:
        y = x
    return y

y=absolute(-10)
y

10

In [23]:
import pyfuns
y=pyfuns.absolute(-10)
y

10

5.2.2 Iterative structures using while or for

In [29]:
def divideby2(n):
    q = n
    while np.remainder(q, 2) == 0:
        q = np.fix(q / 2)

    return q


q=divideby2(5)
q

5

In [28]:
q=pyfuns.divideby2(5)
q

5

In [32]:
x=np.arange(0,1,0.2)
x

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [33]:
p=np.zeros(np.shape(x))
p

array([ 0.,  0.,  0.,  0.,  0.])

In [34]:
p[0]

0.0

In [35]:
np.shape(x)[0]

5

In [37]:
def pdens2(x, m, s):
    N = np.shape(x)[0]
    p = np.zeros(np.shape(x))
    for n in np.arange(0, N - 1):
        p[n] = 1 / (np.sqrt(2 * np.pi) * s) * \
            np.exp(-1 / 2 * np.square((x[n] - m)) / (2 * np.square(s)))

    return p

p=pdens2(x,1,2)
p

array([ 0.18738579,  0.19164976,  0.19503315,  0.19748637,  0.        ])

In [36]:
p=pyfuns.pdens2(x,1,2)
p

array([ 0.18738579,  0.19164976,  0.19503315,  0.19748637,  0.        ])

5.3 Exercises

a)

In [50]:
def oddoreven(n):
    r = np.remainder(n,2)
    return r

In [49]:
ro = oddoreven(1)
re = oddoreven(2)
[ro,re]

[1, 0]

Import function from file

In [46]:
import pyfuns

In [48]:
ro = pyfuns.oddoreven(1)
re = pyfuns.oddoreven(2)
[ro,re]

[1, 0]

b)


In [68]:
from random import randint
y1 = np.array([])
y2 = np.array([])
#[randint(0,9) for p in range(0,10)]
x = np.random.randint(10,size=(1,5))
tmp=np.hstack([y1,1])
tmp

array([ 1.])

In [83]:
from random import randint
y1 = []
y2 = []
x=[randint(0,9) for p in range(0,10)]
x
y1.append(x[1])
y1


[8, 3, 1, 5, 4, 2, 0, 7, 9, 4]

[3]

In [102]:
from random import randint

def oddevensplit(n):
    y1 = []
    y2 = []
    x=[randint(0,9) for p in range(0,n)]
    print(x)
    for i in range(0,n):
        if oddoreven(x[i]):
            print(str(x[i])+' odd')
            y1.append(x[i])
        else:
            print(str(x[i])+' even')
            y2.append(x[i])

    return y1,y2

y1,y2 = oddevensplit(5)
y1
y2

[3, 8, 2, 2, 3]
3 odd
8 even
2 even
2 even
3 odd


[3, 3]

[8, 2, 2]

From file

In [103]:
y1,y2 = pyfuns.oddevensplit(5)

[6, 6, 7, 7, 1]
